[
  {
    "title": "تلك الأيام",
    "price": 6000,
    "isAvailable": true,
    "author": "خالد البسام",
    "category": "67f4adcbb0ebdc4444818154",
    "image": "galees-logo.jpg",
  },
  {
    "title": "وبالحق انزلناه",
    "price": 6000,
    "isAvailable": true,
    "author": "علي بن جابر الفيفي",
    "category": "67f4adcbb0ebdc4444818152",
    "image": "galees-logo.jpg",
  },
  {
    "title": "رسائل من القرآن",
    "price": 6000,
    "isAvailable": true,
    "author": "علي بن جابر الفيفي",
    "category": "67f4adcbb0ebdc4444818152",
    "image": "galees-logo.jpg",
  },
  {
    "title": "رسائل من الصحابة",
    "price": 6000,
    "isAvailable": true,
    "author": "علي بن جابر الفيفي",
    "category": "67f4adcbb0ebdc4444818152",
    "image": "galees-logo.jpg",
  },
  {
    "title": "عندما التقيت عمر",
    "price": 6000,
    "isAvailable": true,
    "author": "أدهم شرقاوي",
    "category": "67f4adcbb0ebdc4444818150",
    "image": "galees-logo.jpg",
  },
  {
    "title": "سلام عليك يا صاحبي",
    "price": 6000,
    "isAvailable": true,
    "author": "أدهم شرقاوي",
    "category": "67f4adcbb0ebdc4444818158",
    "image": "galees-logo.jpg",
  },
  {
    "title": "نحن نقص عليك",
    "price": 6000,
    "isAvailable": true,
    "author": "علي بن جابر الفيفي",
    "category": "67f4adcbb0ebdc4444818152",
    "image": "galees-logo.jpg",
  },
  {
    "title": "خمسين قانون في الحب",
    "price": 6000,
    "isAvailable": true,
    "author": "ياسر الحزيمي",
    "category": "67f4adcbb0ebdc4444818151",
    "image": "galees-logo.jpg",
  },
  {
    "title": "علمتني سورة البقرة",
    "price": 6000,
    "isAvailable": true,
    "author": "هالة سمير",
    "category": "67f4adcbb0ebdc4444818152",
    "image": "galees-logo.jpg",
  },
  {
    "title": "اسرار سورة البقرة",
    "price": 6000,
    "isAvailable": true,
    "author": "هالة سمير",
    "category": "67f4adcbb0ebdc4444818152",
    "image": "galees-logo.jpg",
  },
  {
    "title": "لنا في الحلال لقاء",
    "price": 6000,
    "isAvailable": true,
    "author": "أدهم شرقاوي",
    "category": "67f4adcbb0ebdc4444818150",
    "image": "galees-logo.jpg",
  },
  {
    "title": "كوني صحابية",
    "price": 6000,
    "isAvailable": true,
    "author": "علي بن جابر الفيفي",
    "category": "67f4adcbb0ebdc4444818152",
    "image": "galees-logo.jpg",
  },
  {
    "title": "الى المنكسرة قلوبهم",
    "price": 6000,
    "isAvailable": true,
    "author": "أدهم شرقاوي",
    "category": "67f4adcbb0ebdc4444818158",
    "image": "galees-logo.jpg",
  },
  {
    "title": "كن الشخص الذي يجعلك سعيدا",
    "price": 6000,
    "isAvailable": true,
    "author": "أدهم شرقاوي",
    "category": "67f4adcbb0ebdc4444818151",
    "image": "galees-logo.jpg",
  },
  {
    "title": "فكر مجددا",
    "price": 6000,
    "isAvailable": true,
    "author": "آدم غرانت",
    "category": "67f4adcbb0ebdc4444818151",
    "image": "galees-logo.jpg",
  },
  {
    "title": "المرونة النفسية",
    "price": 6000,
    "isAvailable": true,
    "author": "سوزان ديفيد",
    "category": "67f4adcbb0ebdc4444818156",
    "image": "galees-logo.jpg",
  },
  {
    "title": "متعة أن تكون في العشرين",
    "price": 6000,
    "isAvailable": true,
    "author": "أدهم شرقاوي",
    "category": "67f4adcbb0ebdc4444818158",
    "image": "galees-logo.jpg",
  },
  {
    "title": "جلسات نفسية",
    "price": 6000,
    "isAvailable": true,
    "author": "محمد طه",
    "category": "67f4adcbb0ebdc4444818156",
    "image": "galees-logo.jpg",
  },
  {
    "title": "عقدك النفسية سجنك الابدي",
    "price": 6000,
    "isAvailable": true,
    "author": "محمد طه",
    "category": "67f4adcbb0ebdc4444818156",
    "image": "galees-logo.jpg",
  },
  {
    "title": "احببت وغدا",
    "price": 6000,
    "isAvailable": true,
    "author": "أدهم شرقاوي",
    "category": "67f4adcbb0ebdc4444818150",
    "image": "galees-logo.jpg",
  },
  {
    "title": "العادات السبع للناس الاكثر فاعليه",
    "price": 6000,
    "isAvailable": true,
    "author": "ستيفن كوفي",
    "category": "67f4adcbb0ebdc4444818151",
    "image": "galees-logo.jpg",
  },
  {
    "title": "العادات الذرية",
    "price": 6000,
    "isAvailable": true,
    "author": "جيمس كلير",
    "category": "67f4adcbb0ebdc4444818151",
    "image": "galees-logo.jpg",
  },
  {
    "title": "فن اللامبالاة",
    "price": 6000,
    "isAvailable": true,
    "author": "مارك مانسون",
    "category": "67f4adcbb0ebdc4444818151",
    "image": "galees-logo.jpg",
  },
  {
    "title": "الاب الغني والاب الفقير",
    "price": 6000,
    "isAvailable": true,
    "author": "روبرت كيوساكي",
    "category": "67f4adcbb0ebdc4444818151",
    "image": "galees-logo.jpg",
  },
];
